### ISSUE TITLE
Add exceptional words. 

### ISSUE THREAD

**Issue by abraham891** [knadh/ml2en#7]
How we can add our own exceptional words, so that during conversion these words are printed exactly as in key values.
Like this.....

`var exception = { "ഇന്ത്യ":"india", "ഞാൻ":"njan", ......... };`

How we can implement this?

**Comment by knadh** [comment]
This can be done trivially outside the lib. Before passing an input word to `ml2en()`, look it up in a map like the one in your example, and if it's a match, use that, otherwise, pass to ml2en.
